" Generated by vim-plug
" Thu Feb 25 18:57:29 2021
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['coc.nvim'].commit = '70e5a383cd1c5e39505ef016e8507e7daa4bc7dc'
silent! let g:plugs['editorconfig-vim'].commit = '047c4b455b9d56adee63a52d6d7cdf5bb6521d53'
silent! let g:plugs['fzf.vim'].commit = '02a192ea0bed22a015e005b281e55e0da2a8e496'
silent! let g:plugs['gruvbox'].commit = 'bf2885a95efdad7bd5e4794dd0213917770d79b7'
silent! let g:plugs['neoformat'].commit = 'a75d96054618c47fbafef964d4d705525e8e37b9'
silent! let g:plugs['nerdtree'].commit = 'a1fa4a33bf16b6661e502080fc97788bb98afd35'
silent! let g:plugs['scss-syntax.vim'].commit = 'bda22a93d1dcfcb8ee13be1988560d9bb5bd0fef'
silent! let g:plugs['terminus'].commit = '51c9bf43427af5ddff7352707a2bdab58cac9593'
silent! let g:plugs['typescript-vim'].commit = '67e81e4292186889a1a519e1bf3a600d671237eb'
silent! let g:plugs['vim-colorschemes'].commit = 'fd8f122cef604330c96a6a6e434682dbdfb878c9'
silent! let g:plugs['vim-fugitive'].commit = '6c4c7c9aebc4c65c13f94597e4c9352dbba21fa5'
silent! let g:plugs['vim-git'].commit = '4be54a3e2e300a94f6f7dfa7a6ee9e81245c9886'
silent! let g:plugs['vim-gitgutter'].commit = '1283ec1670d1f4fce37213c5d66924088b2e730c'
silent! let g:plugs['vim-graphql'].commit = '553d125f7b0e56743e80e2439f5cd7f27771a8e3'
silent! let g:plugs['vim-javascript'].commit = '3c90d0cc37bb8b78422f647e62587f498a5dd7bd'
silent! let g:plugs['vim-json'].commit = '3727f089410e23ae113be6222e8a08dd2613ecf2'
silent! let g:plugs['vim-markdown'].commit = '8e5d86f7b85234d3d1b4207dceebc43a768ed5d4'
silent! let g:plugs['vim-mustache-handlebars'].commit = 'fcc1401c2f783c14314ef22517a525a884c549ac'
silent! let g:plugs['vim-node'].commit = 'ede047791792b9530ba1ae73ed86e9671cdd96b8'
silent! let g:plugs['vim-obsession'].commit = '96a3f837c112cb64e0a9857b69f6d6a71041155e'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-rhubarb'].commit = '964d48fd11db7c3a3246885993319d544c7c6fd5'
silent! let g:plugs['vim-sensible'].commit = '2d9f34c09f548ed4df213389caa2882bfe56db58'
silent! let g:plugs['vim-surround'].commit = 'f51a26d3710629d031806305b6c8727189cd1935'
silent! let g:plugs['vim-test'].commit = '5a1cfbbd2b34a64852760497945dd3a5c5df349a'
silent! let g:plugs['vim-tmux-navigator'].commit = '6a1e58c3ca3bc7acca36c90521b3dfae83b2a602'
silent! let g:plugs['vim-toml'].commit = '3c5face8e8944a217af45bc5bb708ff7dfcf1a54'
silent! let g:plugs['vim-unimpaired'].commit = '4afbe5ebf32ad85341b4c02b0e1d8ca96a64c561'

PlugUpdate!

