" Generated by vim-plug
" Mon Jul 19 18:42:49 2021
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['coc.nvim'].commit = '9c3c84735c9bcfd62507d6e2a137f90b1ddaa98a'
silent! let g:plugs['editorconfig-vim'].commit = 'f305bc77faef4b418aee65682d7d147f64cfd5a9'
silent! let g:plugs['fzf.vim'].commit = 'e34f6c129d39b90db44df1107c8b7dfacfd18946'
silent! let g:plugs['gruvbox'].commit = 'bf2885a95efdad7bd5e4794dd0213917770d79b7'
silent! let g:plugs['neoformat'].commit = '3fdfd45119be64945e635bf2406fdb0430cb85df'
silent! let g:plugs['nerdtree'].commit = '2c14ed0e153cdcd0a1c7d1eabec6820bb6b3f8a2'
silent! let g:plugs['scss-syntax.vim'].commit = 'bda22a93d1dcfcb8ee13be1988560d9bb5bd0fef'
silent! let g:plugs['terminus'].commit = 'e8bc19c8156d955762c31d0964eeb7c84889f42e'
silent! let g:plugs['typescript-vim'].commit = '67e81e4292186889a1a519e1bf3a600d671237eb'
silent! let g:plugs['vim-colorschemes'].commit = 'fd8f122cef604330c96a6a6e434682dbdfb878c9'
silent! let g:plugs['vim-fugitive'].commit = 'de6495ae846b2c5913fa85d5464c036c0acdfa34'
silent! let g:plugs['vim-git'].commit = '75047b7d812cbe182ee04f0956bb31ba7efd46b0'
silent! let g:plugs['vim-gitgutter'].commit = '7d9b7125ff2533f6c520573f54e91db2f13a44b0'
silent! let g:plugs['vim-graphql'].commit = 'de5753e3fbd89f2939a43cfc2c6a2313ff129a21'
silent! let g:plugs['vim-javascript'].commit = 'f8345cdb6734aefa5c0f9cb128c9efd005410a43'
silent! let g:plugs['vim-json'].commit = '3727f089410e23ae113be6222e8a08dd2613ecf2'
silent! let g:plugs['vim-markdown'].commit = '8e5d86f7b85234d3d1b4207dceebc43a768ed5d4'
silent! let g:plugs['vim-mustache-handlebars'].commit = 'fcc1401c2f783c14314ef22517a525a884c549ac'
silent! let g:plugs['vim-node'].commit = 'ede047791792b9530ba1ae73ed86e9671cdd96b8'
silent! let g:plugs['vim-obsession'].commit = '82c9ac5e130c92a46e043dd9cd9e5b48d15e286d'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-rhubarb'].commit = 'b4aad6dc43660db554bba2942026fb9965f1a45e'
silent! let g:plugs['vim-sensible'].commit = '2d9f34c09f548ed4df213389caa2882bfe56db58'
silent! let g:plugs['vim-surround'].commit = 'f51a26d3710629d031806305b6c8727189cd1935'
silent! let g:plugs['vim-test'].commit = '849d378a499ada59d3326c166d44f0a118e4bdbf'
silent! let g:plugs['vim-tmux-navigator'].commit = '0cabb1ef01af0986b7bf6fb7acf631debdbbb470'
silent! let g:plugs['vim-toml'].commit = '3c5face8e8944a217af45bc5bb708ff7dfcf1a54'
silent! let g:plugs['vim-unimpaired'].commit = '4afbe5ebf32ad85341b4c02b0e1d8ca96a64c561'

PlugUpdate!

